### ISSUE TITLE
Add support for additional version of Python

### ISSUE THREAD

**Issue by pior** [devbuddy/devbuddy#167]
In some case it would handy to make sure that additional versions of Python are installed on the machine.

Example of use case: when we want to run tests on multiple versions with Tox.

Proposition:

```yaml
up:
  - python: 3.6.5
  - python_extra_versions: [2.7.13, 3.7.0]
```
