### ISSUE TITLE
Support for apt packages

### ISSUE THREAD

**Issue by merwok** [devbuddy/devbuddy#180]
```yaml
 up:
   - apt:
     - libpq-whatever
```

**Comment by pior** [comment]
The `apt` task would be "activated" on OS that use Apt.

This way a project could define this to support multiple platforms:
```yaml
 up:
   - homebrew:
     - somelib
   - apt:
     - somelib12
```
