### ISSUE TITLE
Project manifest are platform specific

### ISSUE THREAD

**Issue by mlhamel** [devbuddy/devbuddy#207]
## Description

`brew` only work on mac
`apt` would only work on debian like os
...

We should find a way to make project manifest compatible for multiple os

### A) Task annotations

Let's add project manifest which would make our `dev.yml` compatible with multiple platforms at the same time.

Example:
```yaml
up:
    - python: 3.6.5
    - homebrew: [osx]
       - curl
       - shellcheck
    - apt: [debian]
       - curl
       - shellcheck
...
```

### B) Task specific conditionals

Every tasks that would be potentially platform specific would have to support it's own set of conditionals

Example:
```yaml
up:
    - python: 3.6.5
    - homebrew:
       - curl
       - shellcheck
       - if: [osx]
    - apt: 
       - curl
       - shellcheck
       - if: [debian]
...
```

### C) Adds support for platform specific sections

Make the `up` generic and then if you multiple different complicated scenario depending of the platform you keep them separated.

```yaml
up:
    - python: 3.6.5

debian:
    - apt:
       - curl
       - shellcheck

osx:
    - homebrew:
       - curl
       - shellcheck

...
```

### D) Ignore tasks for other platforms

Let's make `homebrew` or `apt` tasks silently fail if `brew` or `apt` commands don't exists by example.
