### ISSUE TITLE
Add support for yarnpkg in the node task

### ISSUE THREAD

**Issue by pior** [devbuddy/devbuddy#243]
The _node_ task is installing JS packages with `npm`.
We should also support using yarn:

```yaml
up:
  - node: 10.15.0
      yarn: true
```

```yaml
up:
  - node: 10.15.0
      yarn: 1.12.3
```
