### ISSUE TITLE
Provide a solution to install tools like golangci-lint

### ISSUE THREAD

**Issue by pior** [devbuddy/devbuddy#448]
Two ideas: 

### Project scoped bin dir

- Create dir `${PROJECT_DIR}/.bud/bin/`
- Prepend this dir to `$PATH`
- Set env_var `$PROJECT_BIN` 
- Let the user defines custom tasks to install in `$PROJECT_BIN`
  - The user is responsible for detecting the presence and version

Example:
```yaml
  - custom:
      name: Install golangci-lint
      met?: which golangci-lint && golangci-lint --version | grep -q '1.55.2'
      meet: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ${PROJECT_BIN} v1.55.2
```

### User scoped managed and versioned bin dirs

- Introduce a new task named `install`, similar to `apt` / `homebrew`
  - The `$BINDIR` envvar is set for the tool and the specified version
  - The `$VERSION` envvar is set to the version (this way, the version is only declared once)
- Paths would be like this: `~/.local/share/bud/tools/{{name}}/{{version}}/{{executable-name}}`

```yaml
  - install:
      name: "golangci-lint"
      version: "1.55.2"
      command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ${BINDIR} v1.54.2
```
